# message("Chargement des librairies...")
suppressMessages(library(shiny))
suppressMessages(library(leaflet))
suppressMessages(library(dplyr))
suppressMessages(library(tidyr))
suppressMessages(library(magrittr))
suppressMessages(library(rjson)) # utilisé pour récupérer la palette de couleurs en JSON
suppressMessages(library(sf))
suppressMessages(library(shinyWidgets))
suppressMessages(library(markdown))
suppressMessages(library(stringr))
suppressMessages(library(banR))
suppressMessages(library(glue))
suppressMessages(library(waiter))
suppressMessages(library(stringr))
suppressMessages(library(shinydisconnect))
# install.packages("lwgeom")
suppressMessages(library(lwgeom))
suppressMessages(library(DT))
suppressMessages(library(forcats))
suppressMessages(library(janitor))
suppressMessages(library(yaml))
